import Head from 'next/head'
import styles from '../styles/pages/Home.module.css'

import { useRouter } from 'next/router'
import { useKeenSlider, KeenSliderPlugin} from "keen-slider/react"
import "keen-slider/keen-slider.min.css"
import { useState } from 'react';
import Button from '../components/Button'

export default function Home() {

  const [currentSlide, setCurrentSlide] = useState(0);
  const router = useRouter();
  
  const dados = [
    {
      gameName: 'GUESS THE MAP',
      gameDescription: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae possimus, quisquam laborum voluptates laboriosam officia pariatur autem hic accusantium magnam amet illum repellat nam, cumque dolore ducimus omnis nisi. Amet labore doloremque voluptate dignissimos et eaque quia doloribus libero vel quasi iure ab porro pariatur in a nam distinctio, necessitatibus, iusto ut. Repellendus incidunt error voluptas.',
      urlCard: '/cards/mapCard.png',
      page: '/map'
    },
    {
      gameName: 'WORDLE',
      gameDescription: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae possimus, quisquam laborum voluptates laboriosam officia pariatur autem hic accusantium magnam amet illum repellat nam, cumque dolore ducimus omnis nisi. Amet labore doloremque voluptate dignissimos et eaque quia doloribus libero vel quasi iure ab porro pariatur in a nam distinctio, necessitatibus, iusto ut. Repellendus incidunt error voluptas.',      
    },
    {
      gameName: 'GUESS THE VOICE',
      gameDescription: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae possimus, quisquam laborum voluptates laboriosam officia pariatur autem hic accusantium magnam amet illum repellat nam, cumque dolore ducimus omnis nisi. Amet labore doloremque voluptate dignissimos et eaque quia doloribus libero vel quasi iure ab porro pariatur in a nam distinctio, necessitatibus, iusto ut. Repellendus incidunt error voluptas.',
      urlCard: '/cards/voiceCard.png',
      page: '/voices'
    },
    {
      gameName: 'GUESS THE ABILITY',
      gameDescription: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae possimus, quisquam laborum voluptates laboriosam officia pariatur autem hic accusantium magnam amet illum repellat nam, cumque dolore ducimus omnis nisi. Amet labore doloremque voluptate dignissimos et eaque quia doloribus libero vel quasi iure ab porro pariatur in a nam distinctio, necessitatibus, iusto ut. Repellendus incidunt error voluptas.',      
    }, 
    {
      gameName: 'GUESS THE BUNDLE',
      gameDescription: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae possimus, quisquam laborum voluptates laboriosam officia pariatur autem hic accusantium magnam amet illum repellat nam, cumque dolore ducimus omnis nisi. Amet labore doloremque voluptate dignissimos et eaque quia doloribus libero vel quasi iure ab porro pariatur in a nam distinctio, necessitatibus, iusto ut. Repellendus incidunt error voluptas.',
      urlCard: '/cards/weaponCard.png',
      page: '/bundles'
    }, 
    {
      gameName: 'QUIZZ VALORANT',
      gameDescription: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae possimus, quisquam laborum voluptates laboriosam officia pariatur autem hic accusantium magnam amet illum repellat nam, cumque dolore ducimus omnis nisi. Amet labore doloremque voluptate dignissimos et eaque quia doloribus libero vel quasi iure ab porro pariatur in a nam distinctio, necessitatibus, iusto ut. Repellendus incidunt error voluptas.',      
    }
  ]

  const AdaptiveHeight: KeenSliderPlugin = (slider) => {    
    function updateHeight() {      
      console.log(slider)
      // slider.container.style.height = '300px'
      // slider.slides[slider.track.details.rel].style.height = '500px'

      // slider.container.style.height = slider.slides[slider.track.details.rel].offsetHeight + "px"
    }
    slider.on("created", updateHeight)
    slider.on("slideChanged", updateHeight)
  }

  const [ref, instanceRef] = useKeenSlider<HTMLDivElement>({
    slides: {
      perView: 4,
      origin: "center",
      spacing: 30,
    },    
    loop: true,
    rtl: false,    
    mode: "free-snap",
    initial: 0,
    slideChanged(slider) {
      setCurrentSlide(slider.track.details.rel)
    },    
  }
  ,[AdaptiveHeight]
  )

  return (
    <div className={styles.container}>
      <Head>
        <title>Valdle</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.containerGeral}>                
        <div ref={ref} className={`keen-slider ${styles.slider}`}>
          {
            dados.map((item, index) => (
              <div
                id={`${index}`} 
                key={index} 
                className={`keen-slider__slide ${styles.card}`}
                style={ currentSlide === index ? {
                  boxShadow: '0px 4px 20px rgba(0, 0, 0, 0.5)',                    
                  height: '80vh',                    
                } : {
                  height: '60vh',                                
                }}
              >           
                {
                  item.urlCard ?
                    <img src={item.urlCard} alt="" />
                  :
                    <h3
                      style={{
                        height: '100%',
                        textAlign: 'center',
                        alignItems: 'center',
                        display: 'grid',
                        color: 'var(--white)',
                        fontSize: '3rem'
                      }}
                    >LOADING...</h3>
                }
                
                {
                  (currentSlide === index && item.page) &&
                    <Button
                      text='JOGAR'
                      onClick={() => {
                        item.page &&
                        router.push(item.page)
                      }}
                    />                    
                }                                
              </div>        
            ))
          }                
        </div>    
      
        <div className={styles.backgroundCard}>
          <div>
            <button
              onClick={(e: any) =>
                e.stopPropagation() || instanceRef.current?.prev()                
              }
            >{`<`}</button>
            <p>{currentSlide + 1}/{dados.length}</p>
            <button
              onClick={(e: any) =>
                e.stopPropagation() || instanceRef. current?.next()
              }
            >{`>`}</button>
          </div>          
        </div>

        <div className={styles.containerGameInfo}>
          <div>
            <h1 className={styles.title}>vALDLE</h1>
          </div>
          <div>            
            <h2>
              {dados[currentSlide].gameName}
            </h2>
            <hr />
            <p>
              {dados[currentSlide].gameDescription}
            </p>
          </div>          
        </div>        
      </div>              
    </div>
  )
}
